version: "3.8"
services:

  # micronaut-benchmark
  micronaut-benchmark:
    build: app
    container_name: micronaut-benchmark
    image: blueground/micronaut-benchmark:${BOILERPLATE_SRC_VERSION:-latest}
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8080:8080

  # Postgres db
  postgres:
    image: bitnami/postgresql:11
    container_name: postgres
    env_file: .env
    ports:
      - 5432:5432
